### ISSUE TITLE
config file: add support for annotation regex/globbing [annotations: "*"]

### ISSUE THREAD

**Issue by pascaltimshel** [perslab/CELLECT#33]
add support for annotation regex/globbing in the `.yml` config file.
E.g.
```yaml
HERITABILITY_INPUT:
  - id: mousebrain
    annotations: ["*"]
```
to run h2 analysis type on all annotations.
